services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
    - PYTHONUNBUFFERED=1
    - FASTAPI_ENV=development
    restart: always
    networks:
      - minha-rede-compartilhada

networks:
  minha-rede-compartilhada:
    external: true